export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const GET_POKEMON_BY_ID_SUCCESS = "GET_POKEMON_BY_ID_SUCCESS";
export const GET_POKEMON_BY_ID_FAIL = "GET_POKEMON_BY_ID_FAIL";

export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const GET_POKEMON_LIST_SUCCESS = "GET_POKEMON_LIST_SUCCESS";
export const GET_POKEMON_LIST_FAIL = "GET_POKEMON_LIST_FAIL";

